# Generated by Django 4.2 on 2023-05-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_trailer_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_urls',
            field=models.CharField(default='', max_length=100, verbose_name='Trailer'),
        ),
    ]
