# Generated by Django 4.2 on 2023-05-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_trailer_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_urls',
        ),
    ]
