# Generated by Django 4.2 on 2023-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_trailer_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(default='', max_length=200, verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default=2019, verbose_name='Year'),
        ),
    ]
