# Generated by Django 4.2 on 2023-05-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_poster_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(default='', verbose_name='Poster'),
        ),
    ]
