# Generated by Django 4.2 on 2023-05-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='', max_length=100, verbose_name='Actors'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.CharField(default='', max_length=100, verbose_name='Directors'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(default='', max_length=100, verbose_name='Genres'),
        ),
    ]
