# Generated by Django 4.2 on 2023-05-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_movie_actors_remove_movie_directors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='fees_in_usa',
            field=models.CharField(default='', help_text='enter the dollar amount', max_length=100, verbose_name='US Grossing'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_world',
            field=models.CharField(default='', help_text='enter the dollar amount', max_length=100, verbose_name='World Grossing'),
        ),
    ]
